apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-app-monitor
  namespace: springboot-app
  labels:
    release: prometheus-stack   # Must match Prometheus Helm chart selector
spec:
  namespaceSelector:
    matchNames:
      - springboot-app
  selector:
    matchLabels:
      app: spring-boot-app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
